# **NUMPY**

NumPy is the main package for scientific computing in Python. It performs a wide variety of advanced mathematical operations with high efficiency. In this practice lab you will learn several key NumPy functions that will help you in future assignments, such as creating arrays, slicing, indexing, reshaping and stacking.

In [4]:
#importing the library
import numpy as np

### **n-dimensional array**
The array object in NumPy is called ndarray meaning 'n-dimensional array'. To begin with, you will use one of the most common array types: the one-dimensional array ('1-D'). A 1-D array represents a standard list of values entirely in one dimension. Remember that in NumPy, all of the elements within the array are of the same type.

In [5]:
one_darray = np.array([1,2,3])
print(one_darray)

[1 2 3]


In [6]:
#different ways of creating array
np.array([10,12]) #using array()

array([10, 12])

In [7]:
np.arange(3) # Create an array with 3 integers, starting 0.

array([0, 1, 2])

In [8]:
np.arange(1,20,3) #starts from 1 ends in 20 with increment 3

array([ 1,  4,  7, 10, 13, 16, 19])

In [9]:
np.linspace(1,20,5 ,dtype='int') # five evenly spaced values in the interval from 0 to 100

array([ 1,  5, 10, 15, 20])

In [10]:
ch = np.array(["welcome to math to ml"])
print(ch.dtype) #21 letters

<U21


In [11]:
np.ones(5,dtype = int) #an array with 5 1's

array([1, 1, 1, 1, 1])

In [12]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [13]:
np.empty(3) # Return a new array of shape 3, without initializing entries.

array([6.80143865e-310, 4.94781711e-310, 4.94781680e-310])

In [14]:
np.random.rand(3)

array([0.21143656, 0.22147418, 0.16977115])

### multidimensional array

With NumPy you can also create arrays with more than one dimension. In the above examples, you dealt with 1-D arrays, where you can access their elements using a single index. A multidimensional array has more than one column. Think of a multidimensional array as an excel sheet where each row/column represents a dimension.



In [16]:
two_dim_arr = np.array([[1,2,3],[4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#multi dimensinal array created using reshape()
one_darray = np.array([1,2,3,4,5,6])
one_darray.reshape(2,3)
np.reshape(one_darray,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
two_dim_arr.ndim #dimensions
two_dim_arr.shape #returns (rows,cols)
two_dim_arr.size #returns total num of elements

6